x-base: &base
  volumes:
      - .:/app

services:
  python_3_7:
    <<: *base
    build:
      context: .
      args:
        PYTHON_VERSION: "3.7"
  python_3_8:
    <<: *base
    build:
      context: .
      args:
        PYTHON_VERSION: "3.8"
  python_3_9: &default
    <<: *base
    build:
      context: .
      args:
        PYTHON_VERSION: "3.9"
  test:
    <<: *default
