#!/usr/bin/env bash

# Not a big fan of custom shell scripts like this, but flake8 does not work
# nicely with pytest anymore, and running these tools through pytest might be
# a bit of an anti-pattern to begin with. So sticking with this until a better
# solution is found.

# Trap exit codes until the end of the script, so we can exit with a non-zero
# code when any of the steps failed.
trap 'rc=$?' ERR

target=("pytest_cairo" "tests")

flake8 "${target[@]}"
isort --check-only --color "${target[@]}"
mypy "${target[@]}"
# The above tools are configured statically, but for pytest we want to
# possibility to pass arguments dynamically:
pytest "$@"

exit "${rc:=0}"
