name: run-tests

on: [push]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3_7', '3_8', '3_9']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          python -m pip install tox
          python -m tox -e python_${{ matrix.python-version }}
